module.exports.TABLE_NAMES = {
    USERS: 'users',
    RECIPES: 'recipes',
    TIMES_CATEGORIES: 'times_categories',
    SEASONS_CATEGORIES: 'seasons_categories',
    KOSHER_CATEGORIES: 'kosher_categories',
    HEALTH_CATEGORIES: 'health_categories',
    COOKING_TYPE_CATEGORIES: 'cooking_types_categories',
    ALLERGIES_CATEGORIES: 'allergies_categories',
    KITCHENS_CATEGORIES: 'kitchens_categories',
    FLAVOR_CATEGORIES: 'flavor_categories',
    MEAL_TYPES_CATEGORIES: 'meal_types_categories',
    DIFFICULTY_CATEGORIES: 'difficulty_categories',
    INGREDIENTS: 'ingredients',
  };