module.exports.TABLE_NAMES = {
    USERS: 'users',
    RECIPES: 'recipes',
    TIME_CATEGORIES: 'time_categories',
    // SEASON_CATEGORIES: 'season_categories',
    // KOSHER_CATEGORIES: 'kosher_categories',
    // HEALTH_CATEGORIES: 'health_categories',
    // FOOD_CATEGORIES: 'food_categories',
    // COOKING_TYPE_CATEGORIES: 'cooking_type_categories',
    ALLERGY_CATEGORIES: 'allergy_categories',
    // KITCHENS_CATEGORIES: 'kitchen_style_categories',
    // FLAVOR_CATEGORIES: 'flavor_categories',
    // MEAL_TYPE_CATEGORIES: 'meal_type_categories',
    // DIFFICULTY_CATEGORIES: 'difficulty_categories',
    INGREDIENTS: 'ingredients',
    RECIPE_INGREDIENTS: 'recipe_ingredients',
    RECIPE_ALLERGY_CATEGORIES: 'recipe_allergy_categories',
    // RECIPE_COOKIMG_TYPE_CATEGORIES: 'recipe_cooking_type_categories',
    // RECIPE_DIFFICULTY_CATEGORIES: 'recipe_difficulty_categories',
    // RECIPE_FLAVOR_CATEGORIES: 'recipe_flavor_categories',
    // RECIPE_HEALTH_CATEGORIES: 'recipe_health_categories',
    // RECIPE_KITCHEN_CATEGORIES: 'recipe_kitchen_categories',
    // RECIPE_MEAL_TYPES_CATEGORIES: 'recipe_meal_types_categories',
    // RECIPE_SEASON_CATEGORIES: 'recipe_season_categories',
    RECIPE_TIME_CATEGORIES: 'recipe_time_categories',
    // RECIPE_FOOD_CATEGORIES: 'recipe_food_categories',
    // RECIPE_KOSHER_CATEGORIES: 'recipe_kosher_categories',
    RECIPES_IMAGES: 'recipes_images',
    COMMENTS: 'comments',
    FAVORITES: 'favorites',
  };